/* data-buildings.js
   Base “bâtiments” (56 entrées).
   Ce fichier DOIT être chargé AVANT app.js (dans index.html).

   Note : on a supprimé `tips` ici, car ils seront désormais lus via
   `window.ARCHIQUEST_DETAILS_BY_ID[id].photoTips` (dans detailsById.js).
*/

window.ARCHIQUEST_RAW_DATA = [
  // --- RENNES (NOUVEAUX AJOUTS) ---
  {
    id: 416,
    city: "Rennes",
    type: "Culture",
    name: "FRAC Bretagne",
    architect: "Odile Decq",
    year: "2012",
    address: "19 Avenue André Mussat, 35000 Rennes",
    location_display: "Beauregard",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Frac_Bretagne_Rennes.jpg/800px-Frac_Bretagne_Rennes.jpg"
  },
  {
    id: 417,
    city: "Rennes",
    type: "Logement",
    name: "Le Belvédère",
    architect: "a/LTA architectes",
    year: "2021",
    address: "Rue de Fougères, 35700 Rennes",
    location_display: "Jeanne d'Arc",
    img: null
  },
  {
    id: 418,
    city: "Rennes",
    type: "Bureaux",
    name: "Samsic Siège",
    architect: "Jean-Paul Viguier",
    year: "2021",
    address: "Rue de la Frébardière, 35000 Rennes",
    location_display: "Atalante-ViaSilva",
    img: null
  },
  {
    id: 419,
    city: "Rennes",
    type: "Logement",
    name: "Wonderland",
    architect: "a/LTA architectes",
    year: "2019",
    address: "ZAC de la Courrouze, 35136 Saint-Jacques-de-la-Lande",
    location_display: "La Courrouze",
    img: null
  },
  {
    id: 420,
    city: "Rennes",
    type: "Logement",
    name: "Identity",
    architect: "Jean-Paul Viguier",
    year: "2019",
    address: "Rue de l'Alma, 35000 Rennes",
    location_display: "EuroRennes",
    img: null
  },
  {
    id: 421,
    city: "Rennes",
    type: "Enseignement",
    name: "Pôle associatif de la Marbaudais",
    architect: "Atelier 56S",
    year: "2021",
    address: "32 Rue de la Marbaudais, 35700 Rennes",
    location_display: "Maurepas",
    img: null
  },
  {
    id: 422,
    city: "Rennes",
    type: "Bureaux",
    name: "Le Pixel",
    architect: "Stéphane Kervyn",
    year: "2013",
    address: "ZAC Beauregard-Quincé, 35000 Rennes",
    location_display: "Beauregard",
    img: null
  },
  {
    id: 423,
    city: "Rennes",
    type: "Logement",
    name: "Le Premium",
    architect: "Périphériques Architectes",
    year: "2014",
    address: "Mail François Mitterrand, 35000 Rennes",
    location_display: "Mail Mitterrand",
    img: null
  },
  {
    id: 424,
    city: "Rennes",
    type: "Logement",
    name: "Le Majorelle",
    architect: "Périphériques Architectes",
    year: "2014",
    address: "Mail François Mitterrand, 35000 Rennes",
    location_display: "Mail Mitterrand",
    img: null
  },
  {
    id: 425,
    city: "Rennes",
    type: "Bureaux",
    name: "Tribunal Administratif",
    architect: "Barbarit & Brossard",
    year: "2014",
    address: "3 Contour de la Motte, 35000 Rennes",
    location_display: "Hôtel de la Préfecture",
    img: null
  },
  // --- BREST (7) ---
  {
    id: 101,
    city: "Brest",
    type: "Santé",
    name: "Hôpital Augustin Morvan",
    architect: "Lopez & Gravereaux",
    year: "1936",
    address: "2 Avenue Foch, 29200 Brest",
    location_display: "Av. Foch",
    time: "Matin",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Brest_-_H%C3%B4pital_Morvan_01.jpg/800px-Brest_-_H%C3%B4pital_Morvan_01.jpg",
  },
  {
    id: 102,
    city: "Brest",
    type: "Transport",
    name: "Gare de Brest",
    architect: "Urbain Cassan",
    year: "1930",
    address: "Place du 19ème Régiment d'Infanterie, 29200 Brest",
    location_display: "Centre-ville",
    time: "Crépuscule",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Gare_de_Brest_2014.jpg/800px-Gare_de_Brest_2014.jpg",
  },
  {
    id: 103,
    city: "Brest",
    type: "Culture",
    name: "Les Capucins",
    architect: "Atelier Canal",
    year: "2017",
    address: "25 Rue de Pontaniou, 29200 Brest",
    location_display: "Plateau des Capucins",
    time: "14h-16h",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Ateliers_des_Capucins_-_Brest_-_2017.jpg/800px-Ateliers_des_Capucins_-_Brest_-_2017.jpg",
  },
  {
    id: 104,
    city: "Brest",
    type: "Enseignement",
    name: "Campus CESI",
    architect: "Brulé Architectes",
    year: "2026",
    address: "Technopôle Brest-Iroise, 29200 Brest",
    location_display: "Technopôle",
    time: "Midi",
    img: null,
  },
  {
    id: 105,
    city: "Brest",
    type: "Enseignement",
    name: "Faculté des Sciences",
    architect: "Atelier Rubin",
    year: "Rénov. 2020",
    address: "6 Avenue Victor Le Gorgeu, 29200 Brest",
    location_display: "Bouguen",
    time: "Après-midi",
    img: null,
  },
  {
    id: 106,
    city: "Brest",
    type: "Loisirs",
    name: "Océanopolis (Pavillon)",
    architect: "Non précisé",
    year: "2025",
    address: "Port de Plaisance du Moulin Blanc, 29200 Brest",
    location_display: "Port de Plaisance",
    time: "Golden Hour",
    img: null,
  },
  {
    id: 107,
    city: "Brest",
    type: "Logement",
    name: "Immeubles Art Déco",
    architect: "Crosnier & Philippe",
    year: "1930",
    address: "Rue Jean Jaurès, 29200 Brest",
    location_display: "Centre / Jaurès",
    time: "Grisaille",
    img: null,
  },

  // --- LORIENT (8) ---
  {
    id: 201,
    city: "Lorient",
    type: "Militaire",
    name: "Base de sous-marins",
    architect: "Tech. Allemande",
    year: "1943",
    address: "Rue du Commandant L'Herminier, 56100 Lorient",
    location_display: "Keroman",
    time: "Ciel couvert",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Keroman_III_-_Lorient.jpg/800px-Keroman_III_-_Lorient.jpg",
  },
  {
    id: 202,
    city: "Lorient",
    type: "Logement",
    name: "La Banane",
    architect: "Inconnu",
    year: "1950",
    address: "Place Polig Monjarret, 56100 Lorient",
    location_display: "Pl. Polig Monjarret",
    time: "Fin de journée",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Lorient_-_Place_Polig_Monjarret_-_La_Banane.jpg/800px-Lorient_-_Place_Polig_Monjarret_-_La_Banane.jpg",
  },
  {
    id: 203,
    city: "Lorient",
    type: "Logement",
    name: "Les Échasses",
    architect: "Henri Cordier",
    year: "1963",
    address: "Boulevard Léon Blum, 56100 Lorient",
    location_display: "Le Moustoir",
    time: "Midi",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Lorient_-_Immeuble_sur_pilotis_dit_les_Echasses_-_fa%C3%A7ade_sud.jpg/640px-Lorient_-_Immeuble_sur_pilotis_dit_les_Echasses_-_fa%C3%A7ade_sud.jpg",
  },
  {
    id: 204,
    city: "Lorient",
    type: "Culture",
    name: "Cité de la Voile",
    architect: "Jacques Ferrier",
    year: "2008",
    address: "Lorient La Base, 56100 Lorient",
    location_display: "La Base",
    time: "Golden Hour",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Cite_de_la_voile_Eric_Tabarly_Lorient.jpg/800px-Cite_de_la_voile_Eric_Tabarly_Lorient.jpg",
  },
  {
    id: 205,
    city: "Lorient",
    type: "Logement",
    name: "Quai de Rohan",
    architect: "Roland Castro",
    year: "1996",
    address: "Quai de Rohan, 56100 Lorient",
    location_display: "Quai de Rohan",
    time: "Matin",
    img: null,
  },
  {
    id: 206,
    city: "Lorient",
    type: "Logement",
    name: "Immeubles Os à moelle",
    architect: "Réglain & Guennec",
    year: "1953",
    address: "Square Clisson, 56100 Lorient",
    location_display: "Square Clisson",
    time: "10h-12h",
    img: null,
  },
  {
    id: 207,
    city: "Lorient",
    type: "Public",
    name: "Palais des Congrès",
    architect: "Maurice Ouvré",
    year: "1968",
    address: "Quai Gustave Mansart, 56100 Lorient",
    location_display: "Quai Mansart",
    time: "Après-midi",
    img: null,
  },
  {
    id: 208,
    city: "Lorient",
    type: "Logement",
    name: "Immeuble Plein Ciel",
    architect: "Inconnu",
    year: "1960s",
    address: "Rue Maréchal Foch, 56100 Lorient",
    location_display: "Rue Foch",
    time: "Matin",
    img: null,
  },

  // --- NANTES (13) ---
  {
    id: 310,
    city: "Nantes",
    type: "Bureaux",
    name: "Immeuble Manny",
    architect: "Tetrarc",
    year: "2009",
    address: "19 bis Rue La Noue Bras de Fer, 44200 Nantes",
    location_display: "La Noue Bras de Fer",
    time: "Lumière rasante",
    img: null,
  },
  {
    id: 311,
    city: "Nantes",
    type: "Enseignement",
    name: "ENSA Nantes",
    architect: "Lacaton & Vassal",
    year: "2009",
    address: "6 Quai François Mitterrand, 44200 Nantes",
    location_display: "Quai François Mitterrand",
    time: "Journée",
    img: null,
  },
  {
    id: 312,
    city: "Nantes",
    type: "Culture",
    name: "Musée d'Arts (Cube)",
    architect: "Stanton Williams",
    year: "2017",
    address: "10 Rue Georges Clemenceau, 44000 Nantes",
    location_display: "Rue Georges Clemenceau",
    time: "Temps couvert",
    img: null,
  },
  {
    id: 313,
    city: "Nantes",
    type: "Mémorial",
    name: "Mémorial Abolition Esclavage",
    architect: "Wodiczko + Bonder",
    year: "2012",
    address: "Quai de la Fosse (Souterrain), 44000 Nantes",
    location_display: "Quai de la Fosse",
    time: "Soirée",
    img: null,
  },
  {
    id: 301,
    city: "Nantes",
    type: "Justice",
    name: "Palais de Justice",
    architect: "Jean Nouvel",
    year: "2000",
    address: "19 Quai François Mitterrand, 44200 Nantes",
    location_display: "Île de Nantes",
    time: "Grand Soleil",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Nantes_Palais_de_Justice_2008.jpg/800px-Nantes_Palais_de_Justice_2008.jpg",
  },
  {
    id: 302,
    city: "Nantes",
    type: "Bureaux",
    name: "Tour Bretagne",
    architect: "Devorsine",
    year: "1976",
    address: "Place de Bretagne, 44000 Nantes",
    location_display: "Centre-ville",
    time: "Matin",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Tour_Bretagne_Nantes.jpg/640px-Tour_Bretagne_Nantes.jpg",
  },
  {
    id: 303,
    city: "Nantes",
    type: "Mixte",
    name: "Îlot 5B",
    architect: "RAUM",
    year: "2021",
    address: "Mail Pablo Picasso, 44000 Nantes",
    location_display: "EuroNantes",
    time: "Lumière rasante",
    img: null,
  },
  {
    id: 304,
    city: "Nantes",
    type: "Culture",
    name: "École des Beaux-Arts",
    architect: "Franklin Azzi",
    year: "2017",
    address: "2 Allée Frida Kahlo, 44200 Nantes",
    location_display: "Halles Alstom",
    time: "Journée",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Nantes_-_ESMA_01.jpg/800px-Nantes_-_ESMA_01.jpg",
  },
  {
    id: 305,
    city: "Nantes",
    type: "Culture",
    name: "Le Lieu Unique",
    architect: "P. Bouchain",
    year: "2000",
    address: "2 Quai Ferdinand-Favre, 44000 Nantes",
    location_display: "Canal St-Félix",
    time: "Soirée",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Tour_LU_Nantes_2008.jpg/640px-Tour_LU_Nantes_2008.jpg",
  },
  {
    id: 306,
    city: "Nantes",
    type: "Patrimoine",
    name: "Tour LU",
    architect: "Bluysen",
    year: "1909",
    address: "Quai Ferdinand-Favre, 44000 Nantes",
    location_display: "Canal St-Félix",
    time: "Blue Hour",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Tour_LU_Nantes_2008.jpg/640px-Tour_LU_Nantes_2008.jpg",
  },
  {
    id: 307,
    city: "Nantes",
    type: "Culture",
    name: "Stereolux",
    architect: "Tétrarc",
    year: "2011",
    address: "4 Boulevard Léon Bureau, 44200 Nantes",
    location_display: "Île de Nantes",
    time: "Après-midi",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/La_Fabrique_Nantes_02.jpg/800px-La_Fabrique_Nantes_02.jpg",
  },
  {
    id: 308,
    city: "Nantes",
    type: "Industriel",
    name: "Hangar à Bananes",
    architect: "Charles Friesé",
    year: "1949",
    address: "21 Quai des Antilles, 44200 Nantes",
    location_display: "Pointe de l'Île",
    time: "Coucher de soleil",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Le_Hangar_%C3%A0_Bananes.jpg/800px-Le_Hangar_%C3%A0_Bananes.jpg",
  },
  {
    id: 309,
    city: "Nantes",
    type: "Urbain",
    name: "Quartier Tripode",
    architect: "Portzamparc",
    year: "2010",
    address: "Rue de la Verrerie, 44200 Nantes",
    location_display: "Île de Nantes",
    time: "Variable",
    img: null,
  },

  // --- RENNES & CHANTEPIE (15) ---
  {
    id: 401,
    city: "Rennes",
    type: "Logement",
    name: "Tours Horizons",
    architect: "G. Maillols",
    year: "1970",
    address: "Rue de Brest, 35000 Rennes",
    location_display: "Bourg-l'Évesque",
    time: "Matin/Soir",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Tours_Les_Horizons_-_Rennes.jpg/800px-Tours_Les_Horizons_-_Rennes.jpg",
  },
  {
    id: 402,
    city: "Rennes",
    type: "Culture",
    name: "Champs Libres",
    architect: "Portzamparc",
    year: "2006",
    address: "10 Cours des Alliés, 35000 Rennes",
    location_display: "Esp. Charles de Gaulle",
    time: "Midi",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Les_Champs_Libres_-_Rennes.jpg/800px-Les_Champs_Libres_-_Rennes.jpg",
  },
  {
    id: 403,
    city: "Rennes",
    type: "Bureaux",
    name: "Le Mabilay",
    architect: "Louis Arretche",
    year: "1973",
    address: "2 Rue de la Mabilais, 35000 Rennes",
    location_display: "Quai de la Prévalaye",
    time: "Heure Bleue",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Mabilay_Rennes_2014.jpg/800px-Mabilay_Rennes_2014.jpg",
  },
  {
    id: 404,
    city: "Rennes",
    type: "Bureaux",
    name: "Urban Quartz",
    architect: "Hamonic+Masson",
    year: "2018",
    address: "Rue de l'Alma, 35000 Rennes",
    location_display: "Gare EuroRennes",
    time: "Variable",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Urban_Quartz_Rennes.jpg/800px-Urban_Quartz_Rennes.jpg",
  },
  {
    id: 405,
    city: "Rennes",
    type: "Logement",
    name: "Barre Saint-Just",
    architect: "G. Maillols",
    year: "1969",
    address: "Rue Jean Boucher, 35000 Rennes",
    location_display: "Thabor",
    time: "Après-midi",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Barre_Saint-Just_Rennes.jpg/800px-Barre_Saint-Just_Rennes.jpg",
  },
  {
    id: 406,
    city: "Rennes",
    type: "Logement",
    name: "Cap Mail",
    architect: "Jean Nouvel",
    year: "2015",
    address: "Mail François Mitterrand, 35000 Rennes",
    location_display: "Bord de Vilaine",
    time: "Coucher de soleil",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cap_Mail_Rennes.jpg/800px-Cap_Mail_Rennes.jpg",
  },
  {
    id: 407,
    city: "Rennes",
    type: "Culture",
    name: "Couvent des Jacobins",
    architect: "Jean Guervilly",
    year: "2018",
    address: "Place Sainte-Anne, 35000 Rennes",
    location_display: "Centre historique",
    time: "Journée",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Couvent_des_Jacobins_Rennes_sud.jpg/800px-Couvent_des_Jacobins_Rennes_sud.jpg",
  },
  {
    id: 408,
    city: "Rennes",
    type: "Culture",
    name: "TNB",
    architect: "Antoine Stinco",
    year: "2008",
    address: "1 Rue Saint-Hélier, 35000 Rennes",
    location_display: "Centre-ville",
    time: "Temps gris",
    img: null,
  },
  {
    id: 409,
    city: "Rennes",
    type: "Bureaux",
    name: "Tour de l'Éperon",
    architect: "Louis Arretche",
    year: "1970",
    address: "Rue du Puits Mauger, 35000 Rennes",
    location_display: "Colombier",
    time: "Matin",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Tour_de_l%27%C3%89peron_-_Rennes.jpg/640px-Tour_de_l%27%C3%89peron_-_Rennes.jpg",
  },
  {
    id: 410,
    city: "Rennes",
    type: "Logement",
    name: "Ascension Paysagère",
    architect: "Bertrand Schippan",
    year: "2022",
    address: "Rue de l'Alma, 35000 Rennes",
    location_display: "Octroi",
    time: "Golden Hour",
    img: null,
  },
  {
    id: 411,
    city: "Rennes",
    type: "Logement",
    name: "Immeuble Chromosome",
    architect: "Mille Architectes",
    year: "2021",
    address: "Boulevard de la Robiquette, 35000 Rennes",
    location_display: "Beauregard",
    time: "Midi",
    img: null,
  },
  {
    id: 412,
    city: "Chantepie",
    type: "Logement",
    name: "Eden Square",
    architect: "Christian Hauvette",
    year: "2012",
    address: "Avenue André Bonnin, 35135 Chantepie",
    location_display: "Chantepie",
    time: "Soleil",
    img: null,
  },
  {
    id: 413,
    city: "Rennes",
    type: "Logement",
    name: "La Caravelle",
    architect: "G. Maillols",
    year: "1969",
    address: "Quai d'Ille-et-Rance, 35000 Rennes",
    location_display: "Bourg-l'Évesque",
    time: "Matin",
    img: null,
  },
  {
    id: 414,
    city: "Rennes",
    type: "Bureaux",
    name: "Cap Courrouze",
    architect: "Jacques Ferrier",
    year: "2015",
    address: "Rue Samuel de Champlain, 35000 Rennes",
    location_display: "La Courrouze",
    time: "Après-midi",
    img: null,
  },
  {
    id: 415,
    city: "Rennes",
    type: "Enseignement",
    name: "Campus Santé",
    architect: "ENIA",
    year: "2025",
    address: "Avenue du Professeur Léon Bernard, 35000 Rennes",
    location_display: "Villejean",
    time: "Soir",
    img: null,
  },

  // --- SAINT-NAZAIRE (4) ---
  {
    id: 501,
    city: "Saint-Nazaire",
    type: "Culture",
    name: "Théâtre",
    architect: "K-architectures",
    year: "2012",
    address: "Rue des Frères Pereire, 44600 Saint-Nazaire",
    location_display: "Ville-Port",
    time: "Lumière latérale",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Le_Th%C3%A9%C3%A2tre_Saint-Nazaire_03.jpg/800px-Le_Th%C3%A9%C3%A2tre_Saint-Nazaire_03.jpg",
  },
  {
    id: 502,
    city: "Saint-Nazaire",
    type: "Culture",
    name: "LiFE / Base",
    architect: "Guerre / Réhab",
    year: "1941",
    address: "Boulevard de la Légion d'Honneur, 44600 Saint-Nazaire",
    location_display: "Port",
    time: "Journée",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Base_sous-marine_de_Saint-Nazaire_06.JPG/800px-Base_sous-marine_de_Saint-Nazaire_06.JPG",
  },
  {
    id: 503,
    city: "Saint-Nazaire",
    type: "Commerce",
    name: "Halles Centrales",
    architect: "Cabinet Dommée",
    year: "1956",
    address: "Place du Commerce, 44600 Saint-Nazaire",
    location_display: "Centre-ville",
    time: "Dimanche",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Halles_Saint-Nazaire_01.jpg/800px-Halles_Saint-Nazaire_01.jpg",
  },
  {
    id: 504,
    city: "Saint-Nazaire",
    type: "Culture",
    name: "Le Grand Café",
    architect: "XIXe",
    year: "1997",
    address: "Place des Quatre z'Horloges, 44600 Saint-Nazaire",
    location_display: "Centre-ville",
    time: "Journée",
    img: null,
  },

  // --- QUIMPER (1) ---
  {
    id: 601,
    city: "Quimper",
    type: "Commerce",
    name: "Ty Kodak",
    architect: "O. Mordrelle",
    year: "1933",
    address: "33 Boulevard Amiral de Kerguelen, 29000 Quimper",
    location_display: "Bd de Kerguelen",
    time: "Matin",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Quimper_-_Boulevard_de_Kerguelen_-_Immeuble_Ty_Kodak_-_002.jpg/640px-Quimper_-_Boulevard_de_Kerguelen_-_Immeuble_Ty_Kodak_-_002.jpg",
  },

  // --- SAINT-BRIEUC (2) ---
  {
    id: 701,
    city: "Saint-Brieuc",
    type: "Admin",
    name: "Préfecture",
    architect: "Maurice Silvy",
    year: "1973",
    address: "1 Place du Général de Gaulle, 22000 Saint-Brieuc",
    location_display: "Pl. Général de Gaulle",
    time: "Journée",
    img: null,
  },
  {
    id: 702,
    city: "Saint-Brieuc",
    type: "Santé",
    name: "Hôpital Yves Le Foll",
    architect: "AIA",
    year: "2022",
    address: "10 Rue Marcel Proust, 22000 Saint-Brieuc",
    location_display: "Brézillet",
    time: "Matin",
    img: null,
  },

  // --- VANNES (6) ---
  {
    id: 801,
    city: "Vannes",
    type: "Santé",
    name: "Médicentre du Ténénio",
    architect: "Arcau",
    year: "2005",
    address: "10 Rue du Docteur Joseph Audic, 56000 Vannes",
    location_display: "Ténénio",
    time: "Midi",
    img: null,
  },
  {
    id: 802,
    city: "Vannes",
    type: "Culture",
    name: "Médiathèque",
    architect: "Arcau",
    year: "2008",
    address: "Rue de Ploeren, 56000 Vannes",
    location_display: "Kercado",
    time: "Après-midi",
    img: null,
  },
  {
    id: 803,
    city: "Vannes",
    type: "Justice",
    name: "Palais de Justice",
    architect: "Arcau",
    year: "2005",
    address: "Place de la République, 56000 Vannes",
    location_display: "Centre-ville",
    time: "Zénithal",
    img: null,
  },
  {
    id: 804,
    city: "Vannes",
    type: "Santé",
    name: "Centre de soins L'Ancre",
    architect: "Sera 2",
    year: "2009",
    address: "Rue du 19 Mars 1962, 56000 Vannes",
    location_display: "Vannes Nord",
    time: "Matin",
    img: null,
  },
  {
    id: 805,
    city: "Vannes",
    type: "Culture",
    name: "Espace Culturel",
    architect: "Chochon & Pierre",
    year: "2008",
    address: "Rue des 2 Moulins, 56000 Vannes",
    location_display: "Centre",
    time: "Journée",
    img: null,
  },
  {
    id: 806,
    city: "Vannes",
    type: "Enfance",
    name: "Maison de l'Enfance",
    architect: "Arcau",
    year: "2004",
    address: "Place Jules Gillet, 56000 Vannes",
    location_display: "Ménimur",
    time: "Matin",
    img: null,
  },
];
